Server:
  RunMode: debug
  HttpPort: 1016
  ReadTimeout: 60
  WriteTimeout: 60
Database:
  DBType: mysql
  Username: root
  Password: 123456
  # rule-server-mysql
  Host: host.docker.internal:13306
  # Host: 127.0.0.1:13306
  DBName: rule-server
  Charset: utf8mb4
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
