Server:
  RunMode: debug
  HttpPort: 1016
  ReadTimeout: 60
  WriteTimeout: 60
Database:
  DBType: mysql
  Username: root
  Password: 123456
  # Host: 127.0.0.1:13306
  # 使用docker服务名作为hostname
  Host: mysql:3306
  DBName: rule-server
  Charset: utf8mb4
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
